[profile.default]
src = 'contracts'
test = 'test/foundry'
script = 'script'
out = 'out'
libs = ['lib']
remappings = []

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
gnosis = "${RPC_GNOSIS}"

[etherscan]
mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}
gnosis={key="${ETHERSCAN_API_KEY_GNOSIS}",chainId=100}

[fuzz]
runs=1000

# See more config options https://github.com/gakonst/foundry/tree/master/config
